name: BlockBall
version: 6.42.1
author: Shynixn
website: https://www.spigotmc.org/members/shynixn.63455/
main: com.github.shynixn.blockball.BlockBallPlugin
softdepend: [ BossBarAPI, PlaceholderAPI, Vault ]
libraries:
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-api:2.15.0
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-core:2.15.0
  - com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.3.0
  - com.fasterxml.jackson.core:jackson-databind:2.3.0
  - com.google.inject:guice:7.0.0
  - com.google.code.gson:gson:2.10.1
  - com.zaxxer:HikariCP:5.0.1
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.23
  - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3
  - aopalliance:aopalliance:1.0
commands:
  blockball:
    description: Opens the arena creation UI.
    usage: /<command>
    permission: blockball.command.admin
    permission-message: You don't have permission.
  blockballstop:
    description: Stops a running blockball game.
    usage: /<command> <id/name>
    permission: blockball.command.admin
    permission-message: You don't have permission.
  blockballreload:
    description: Reloads Blockball configuration and restarts all games.
    usage: /<command>
    permission: blockball.command.reload
    permission-message: You don't have permission.
